# Generated by Django 5.0.6 on 2024-05-13 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_newsbden_commentsen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsen',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.newsbden'),
        ),
    ]
