# Generated by Django 5.0.6 on 2024-05-21 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_posnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosNewsEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.newsbd')),
            ],
        ),
    ]
