# Generated by Django 5.0.6 on 2024-05-21 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_posnewsen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posnewsen',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.newsbden'),
        ),
    ]
