# Generated by Django 5.0.6 on 2024-05-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_posnewsen_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PosNewsEN',
        ),
    ]
